In [1]:
import numpy as np
from datascience import *
import random
import pandas as pd
import os 

# These lines do some fancy plotting magic
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore')
from datetime import datetime

In [2]:
#generates mock distribution of ratings
def generateValue():
  r = random.random()
  if r < 0.1:
    return 1
  elif  r < 0.3:
    return 2
  elif r < 0.6:
    return 3
  elif r < 0.9:
    return 4
  else:
    return 5 

#number of reviews 
big_size = 500

ratings = make_array()
for i in range(big_size):
  ratings = np.append(ratings, generateValue())

ratings

array([ 4.,  3.,  5.,  4.,  3.,  3.,  4.,  2.,  1.,  2.,  5.,  4.,  2.,
        5.,  4.,  5.,  4.,  3.,  2.,  3.,  3.,  3.,  3.,  4.,  3.,  2.,
        4.,  4.,  1.,  2.,  1.,  4.,  4.,  3.,  3.,  4.,  2.,  4.,  4.,
        4.,  3.,  1.,  2.,  3.,  4.,  2.,  5.,  2.,  1.,  4.,  3.,  2.,
        2.,  4.,  4.,  3.,  2.,  4.,  4.,  2.,  4.,  3.,  4.,  4.,  3.,
        5.,  5.,  3.,  4.,  2.,  3.,  3.,  2.,  3.,  4.,  4.,  2.,  3.,
        4.,  4.,  4.,  4.,  2.,  4.,  5.,  1.,  3.,  5.,  4.,  4.,  4.,
        3.,  1.,  4.,  2.,  4.,  4.,  3.,  5.,  2.,  2.,  4.,  4.,  4.,
        3.,  4.,  3.,  3.,  4.,  5.,  4.,  3.,  3.,  1.,  4.,  3.,  3.,
        3.,  3.,  3.,  3.,  4.,  2.,  2.,  4.,  2.,  4.,  3.,  4.,  3.,
        3.,  2.,  4.,  1.,  4.,  4.,  4.,  3.,  3.,  4.,  3.,  3.,  3.,
        2.,  5.,  3.,  4.,  5.,  3.,  5.,  4.,  5.,  4.,  1.,  4.,  4.,
        2.,  3.,  2.,  3.,  1.,  2.,  1.,  4.,  4.,  5.,  5.,  3.,  3.,
        2.,  3.,  5.,  1.,  4.,  3.,  4.,  4.,  3.,  2.,  1.,  2

In [3]:
reviews = Table().with_column("ratings", ratings)
reviews

ratings
4
3
5
4
3
3
4
2
1
2
... (490 rows omitted)

In [4]:
#simulated data of importances, in full model would use real data 
importance = np.random.gumbel(150, 50, big_size)
importance

array([ 169.49198585,  111.57398216,  304.75992838,  126.2385845 ,
        149.92733155,  287.36444911,  386.34184174,  215.18900585,
        217.94559453,  100.33015823,  105.82505474,  112.96582956,
         78.00361969,  122.8053056 ,  192.90907792,  220.94463508,
        179.86556906,  118.05742332,  181.78694759,  162.49211845,
        176.02638002,  216.31814194,  240.41697686,  345.3036211 ,
        265.71174599,  127.29642408,  177.08261322,  136.55851164,
        212.96638395,  141.74077546,  257.67886782,  218.00729292,
        147.06022896,  122.10396004,  237.81799075,  346.30306581,
         88.16204536,  177.46415251,  163.62870253,  188.1481927 ,
        139.35816622,  185.62459815,  148.91152413,  191.13362961,
        160.8131272 ,   92.60391269,  155.70908947,  161.70619193,
        101.65905569,   98.46110668,  166.44475209,  202.79282696,
        169.23091973,  262.54669673,  115.99433074,  142.82733497,
        292.16149653,  159.78009255,  162.47457928,  217.02921

In [5]:
reviews = reviews.with_column("importance", importance)
reviews

ratings | importance
4       | 169.492
3       | 111.574
5       | 304.76
4       | 126.239
3       | 149.927
3       | 287.364
4       | 386.342
2       | 215.189
1       | 217.946
2       | 100.33
... (490 rows omitted)

In [6]:
#random variables are used for simulating random similarities
random_variables = np.random.random_integers(1, 2000, big_size)
reviews = reviews.with_column("random var", random_variables)

In [7]:

random_variables
def find_similarity(var):
  diff_arr = make_array()
  for r in random_variables:
    diff_arr = np.append(diff_arr, abs(r - var))
  return 2000 - diff_arr


In [8]:
similarity = find_similarity(11)
similarity

array([  846.,   361.,   561.,   183.,  1947.,   336.,  1392.,  1673.,
        1523.,  1104.,    99.,  1601.,  1767.,  1570.,   816.,  1801.,
          62.,  1789.,  1611.,   678.,  1919.,   733.,  1424.,   866.,
        1333.,   840.,  1615.,   959.,   410.,  1081.,  1764.,  1791.,
         328.,  1698.,   728.,   184.,   853.,  1835.,   589.,  1375.,
         243.,  1217.,   201.,  1981.,   337.,   644.,   709.,  1501.,
        1908.,   355.,   874.,   591.,   936.,  1312.,   637.,   180.,
        1877.,   753.,  1221.,  1345.,  1832.,  1323.,   722.,   362.,
        1902.,  1980.,  1933.,  1012.,   787.,   415.,  1495.,    20.,
        1721.,  1887.,  1178.,  1026.,  1121.,   226.,  1103.,   279.,
        1672.,   386.,  1912.,  1395.,  1887.,    44.,  1455.,  1245.,
         135.,  1165.,  1544.,  1601.,   787.,  1056.,   671.,   668.,
        1581.,   582.,   761.,   956.,   709.,   411.,   314.,   137.,
         222.,   439.,   244.,   524.,   909.,  1465.,   814.,   126.,
      

In [9]:
similarities = reviews.apply(find_similarity, "random var")
reviews = reviews.with_column("similarities", similarities)
reviews

ratings | importance | random var | similarities
4       | 169.492    | 1165       | [ 2000.  1515.  1715.  1337.   899.  1490.  1454.  1173. ...
3       | 111.574    | 1650       | [ 1515.  2000.  1800.  1822.   414.  1975.   969.   688. ...
5       | 304.76     | 1450       | [ 1715.  1800.  2000.  1622.   614.  1775.  1169.   888. ...
4       | 126.239    | 1828       | [ 1337.  1822.  1622.  2000.   236.  1847.   791.   510. ...
3       | 149.927    | 64         | [  899.   414.   614.   236.  2000.   389.  1445.  1726. ...
3       | 287.364    | 1675       | [ 1490.  1975.  1775.  1847.   389.  2000.   944.   663. ...
4       | 386.342    | 619        | [ 1454.   969.  1169.   791.  1445.   944.  2000.  1719. ...
2       | 215.189    | 338        | [ 1173.   688.   888.   510.  1726.   663.  1719.  2000. ...
1       | 217.946    | 488        | [ 1323.   838.  1038.   660.  1576.   813.  1869.  1850. ...
2       | 100.33     | 907        | [ 1742.  1257.  1457.  1079.  1157.  1232.  1712.  1431. ...
... (490 rows omitted)

In [10]:
similarities

array([[ 2000.,  1515.,  1715., ...,  1946.,  1448.,  1221.],
       [ 1515.,  2000.,  1800., ...,  1569.,   963.,   736.],
       [ 1715.,  1800.,  2000., ...,  1769.,  1163.,   936.],
       ..., 
       [ 1946.,  1569.,  1769., ...,  2000.,  1394.,  1167.],
       [ 1448.,   963.,  1163., ...,  1394.,  2000.,  1773.],
       [ 1221.,   736.,   936., ...,  1167.,  1773.,  2000.]])

In [11]:
for i in range(len(similarities)):
  for j in range(len(similarities[0])):
    if i == j:
      similarities[i][j] = 0

reviews = reviews.with_column("similarities", similarities)
reviews

ratings | importance | random var | similarities
4       | 169.492    | 1165       | [    0.  1515.  1715.  1337.   899.  1490.  1454.  1173. ...
3       | 111.574    | 1650       | [ 1515.     0.  1800.  1822.   414.  1975.   969.   688. ...
5       | 304.76     | 1450       | [ 1715.  1800.     0.  1622.   614.  1775.  1169.   888. ...
4       | 126.239    | 1828       | [ 1337.  1822.  1622.     0.   236.  1847.   791.   510. ...
3       | 149.927    | 64         | [  899.   414.   614.   236.     0.   389.  1445.  1726. ...
3       | 287.364    | 1675       | [ 1490.  1975.  1775.  1847.   389.     0.   944.   663. ...
4       | 386.342    | 619        | [ 1454.   969.  1169.   791.  1445.   944.     0.  1719. ...
2       | 215.189    | 338        | [ 1173.   688.   888.   510.  1726.   663.  1719.     0. ...
1       | 217.946    | 488        | [ 1323.   838.  1038.   660.  1576.   813.  1869.  1850. ...
2       | 100.33     | 907        | [ 1742.  1257.  1457.  1079.  1157.  1232.  1712.  1431. ...
... (490 rows omitted)

In [12]:
sim_sums = reviews.apply(sum, "similarities")
reviews = reviews.with_column("similarity sum", sim_sums)
reviews

ratings | importance | random var | similarities                                                 | similarity sum
4       | 169.492    | 1165       | [    0.  1515.  1715.  1337.   899.  1490.  1454.  1173. ... | 749173
3       | 111.574    | 1650       | [ 1515.     0.  1800.  1822.   414.  1975.   969.   688. ... | 654507
5       | 304.76     | 1450       | [ 1715.  1800.     0.  1622.   614.  1775.  1169.   888. ... | 709021
4       | 126.239    | 1828       | [ 1337.  1822.  1622.     0.   236.  1847.   791.   510. ... | 588733
3       | 149.927    | 64         | [  899.   414.   614.   236.     0.   389.  1445.  1726. ... | 516717
3       | 287.364    | 1675       | [ 1490.  1975.  1775.  1847.   389.     0.   944.   663. ... | 646257
4       | 386.342    | 619        | [ 1454.   969.  1169.   791.  1445.   944.     0.  1719. ... | 700575
2       | 215.189    | 338        | [ 1173.   688.   888.   510.  1726.   663.  1719.     0. ... | 624289
1       | 217.946    | 488        | [ 1323.   838.  1038.   660.  1576.   813.  1869.  1850. ... | 668637
2       | 100.33     | 907        | [ 1742.  1257.  1457.  1079.  1157.  1232.  1712.  1431. ... | 744183
... (490 rows omitted)

In [13]:
def find_proportion(similarities, total_sum):
  return similarities / total_sum

similarity_proportions = reviews.apply(find_proportion, "similarities", "similarity sum")
similarity_proportions

array([[ 0.        ,  0.00202223,  0.00228919, ...,  0.00259753,
         0.0019328 ,  0.0016298 ],
       [ 0.00231472,  0.        ,  0.00275016, ...,  0.00239722,
         0.00147134,  0.00112451],
       [ 0.00241883,  0.00253871,  0.        , ...,  0.00249499,
         0.00164029,  0.00132013],
       ..., 
       [ 0.00261222,  0.00210616,  0.00237463, ...,  0.        ,
         0.00187124,  0.00156653],
       [ 0.00207083,  0.00137722,  0.00166324, ...,  0.0019936 ,
         0.        ,  0.00253562],
       [ 0.00190904,  0.00115074,  0.00146344, ...,  0.00182461,
         0.00277209,  0.        ]])

In [14]:
for i in range(len(similarity_proportions)):
  for j in range(len(similarity_proportions)):
    if i == j:
      similarity_proportions[i][j] = 0.9
    else:
      similarity_proportions[i][j] = similarity_proportions[i][j] * 0.1

reviews = reviews.with_column("similarity proportions", similarity_proportions)
reviews

ratings | importance | random var | similarities                                                 | similarity sum | similarity proportions
4       | 169.492    | 1165       | [    0.  1515.  1715.  1337.   899.  1490.  1454.  1173. ... | 749173         | [  9.00000000e-01   2.02222985e-04   2.28919088e-04   1. ...
3       | 111.574    | 1650       | [ 1515.     0.  1800.  1822.   414.  1975.   969.   688. ... | 654507         | [  2.31471932e-04   9.00000000e-01   2.75016157e-04   2. ...
5       | 304.76     | 1450       | [ 1715.  1800.     0.  1622.   614.  1775.  1169.   888. ... | 709021         | [  2.41882822e-04   2.53871183e-04   9.00000000e-01   2. ...
4       | 126.239    | 1828       | [ 1337.  1822.  1622.     0.   236.  1847.   791.   510. ... | 588733         | [  2.27097853e-04   3.09478151e-04   2.75506894e-04   9. ...
3       | 149.927    | 64         | [  899.   414.   614.   236.     0.   389.  1445.  1726. ... | 516717         | [  1.73983051e-04   8.01212269e-05   1.18827134e-04   4. ...
3       | 287.364    | 1675       | [ 1490.  1975.  1775.  1847.   389.     0.   944.   663. ... | 646257         | [  2.30558431e-04   3.05605974e-04   2.74658534e-04   2. ...
4       | 386.342    | 619        | [ 1454.   969.  1169.   791.  1445.   944.     0.  1719. ... | 700575         | [  2.07543803e-04   1.38314956e-04   1.66862934e-04   1. ...
2       | 215.189    | 338        | [ 1173.   688.   888.   510.  1726.   663.  1719.     0. ... | 624289         | [  1.87893748e-04   1.10205370e-04   1.42241814e-04   8. ...
1       | 217.946    | 488        | [ 1323.   838.  1038.   660.  1576.   813.  1869.  1850. ... | 668637         | [  1.97865209e-04   1.25329588e-04   1.55241185e-04   9. ...
2       | 100.33     | 907        | [ 1742.  1257.  1457.  1079.  1157.  1232.  1712.  1431. ... | 744183         | [  2.34082208e-04   1.68910066e-04   1.95785176e-04   1. ...
... (490 rows omitted)

In [15]:
matriixx = np.asmatrix(similarity_proportions)
matriixx

matrix([[  9.00000000e-01,   2.02222985e-04,   2.28919088e-04, ...,
           2.59753088e-04,   1.93279790e-04,   1.62979712e-04],
        [  2.31471932e-04,   9.00000000e-01,   2.75016157e-04, ...,
           2.39722417e-04,   1.47133644e-04,   1.12451051e-04],
        [  2.41882822e-04,   2.53871183e-04,   9.00000000e-01, ...,
           2.49498957e-04,   1.64028992e-04,   1.32013015e-04],
        ..., 
        [  2.61222430e-04,   2.10615618e-04,   2.37462733e-04, ...,
           9.00000000e-01,   1.87124392e-04,   1.56652916e-04],
        [  2.07082863e-04,   1.37721545e-04,   1.66324150e-04, ...,
           1.99360160e-04,   9.00000000e-01,   2.53562097e-04],
        [  1.90903846e-04,   1.15073899e-04,   1.46343980e-04, ...,
           1.82460924e-04,   2.77209270e-04,   9.00000000e-01]])

In [16]:
importance

array([ 169.49198585,  111.57398216,  304.75992838,  126.2385845 ,
        149.92733155,  287.36444911,  386.34184174,  215.18900585,
        217.94559453,  100.33015823,  105.82505474,  112.96582956,
         78.00361969,  122.8053056 ,  192.90907792,  220.94463508,
        179.86556906,  118.05742332,  181.78694759,  162.49211845,
        176.02638002,  216.31814194,  240.41697686,  345.3036211 ,
        265.71174599,  127.29642408,  177.08261322,  136.55851164,
        212.96638395,  141.74077546,  257.67886782,  218.00729292,
        147.06022896,  122.10396004,  237.81799075,  346.30306581,
         88.16204536,  177.46415251,  163.62870253,  188.1481927 ,
        139.35816622,  185.62459815,  148.91152413,  191.13362961,
        160.8131272 ,   92.60391269,  155.70908947,  161.70619193,
        101.65905569,   98.46110668,  166.44475209,  202.79282696,
        169.23091973,  262.54669673,  115.99433074,  142.82733497,
        292.16149653,  159.78009255,  162.47457928,  217.02921

In [17]:
new_importance = np.array(np.dot(importance, matriixx))
for i in range(500):
  new_importance = np.array(np.dot(new_importance, matriixx))
new_importance
  

array([[ 199.83923899,  174.58741946,  189.12883549,  157.04243838,
         137.83242596,  172.38676123,  186.87589496,  166.5268752 ,
         178.35654681,  198.5081742 ,  147.2699154 ,  172.54200767,
         157.75465141,  174.94806066,  199.28600685,  154.30135185,
         142.7378932 ,  155.54172285,  171.74176831,  194.81266887,
         141.22170637,  196.92850172,  184.90303821,  200.09264812,
         190.20329019,  199.74321027,  171.4195386 ,  200.37166491,
         178.5528722 ,  198.99098528,  158.05234045,  155.33846205,
         171.65800993,  164.30327678,  196.75244906,  157.15447189,
         199.93846867,  150.64052356,  190.66262758,  187.8649908 ,
         163.40274076,  195.28107564,  159.02703198,  133.4924612 ,
         172.47692153,  193.33649401,  196.03916905,  179.88713795,
         142.50635728,  174.07526627,  200.17533952,  190.76505822,
         200.41967927,  191.27827839,  193.01906573,  156.70473737,
         146.02314249,  197.59483435,  195.14183

In [18]:
final_tbl = reviews.select("ratings", "importance")
final_tbl = final_tbl.with_column("steady importance",new_importance[0])
final_tbl

ratings | importance | steady importance
4       | 169.492    | 199.839
3       | 111.574    | 174.587
5       | 304.76     | 189.129
4       | 126.239    | 157.042
3       | 149.927    | 137.832
3       | 287.364    | 172.387
4       | 386.342    | 186.876
2       | 215.189    | 166.527
1       | 217.946    | 178.357
2       | 100.33     | 198.508
... (490 rows omitted)

In [19]:
total_importance = sum(final_tbl.column("steady importance"))
proportional_importance = final_tbl.column("steady importance") / total_importance
proportional_importance
final_tbl = final_tbl.with_column("proportional importance", proportional_importance)
final_tbl
cool_average = sum(final_tbl.column("ratings") * final_tbl.column("proportional importance"))
cool_average

3.1962883721163342

In [20]:
vanilla_average_rating = np.mean(final_tbl.column("ratings"))
vanilla_average_rating

3.198

In [21]:
final_tbl

ratings | importance | steady importance | proportional importance
4       | 169.492    | 199.839           | 0.00225089
3       | 111.574    | 174.587           | 0.00196647
5       | 304.76     | 189.129           | 0.00213025
4       | 126.239    | 157.042           | 0.00176885
3       | 149.927    | 137.832           | 0.00155248
3       | 287.364    | 172.387           | 0.00194168
4       | 386.342    | 186.876           | 0.00210488
2       | 215.189    | 166.527           | 0.00187568
1       | 217.946    | 178.357           | 0.00200892
2       | 100.33     | 198.508           | 0.0022359
... (490 rows omitted)

In [22]:
os.system("touch results.csv")
final_tbl.to_csv('results.csv')